### PR TITLE
Fixes incorrect team in Pattern/Array by calling the wrong ctor unintended

### LINKED ISSUE #353: dash::Array storing the wrong team?
I am still debugging #292 (with increasing desperation). I found the following strange behavior

```
TEST_F(ArrayTest, TeamSplit)
{
  auto & team_all = dash::Team::All();
  auto   ext_x    = team_all.size();

  if(team_all.size() < 2){
    SKIP_TEST();
  }
  if(!team_all.is_leaf()){
    LOG_MESSAGE("team is already splitted. Skip test");
    SKIP_TEST();
  }

  dash::barrier();

  LOG_MESSAGE("Splitting team ...");
  auto & myteam = team_all.split(2);
  LOG_MESSAGE("... Team split finished");

  dash::Array<double> array_a(ext_x, myteam);
  ASSERT_EQ_U(array_a.team(), myteam); // << this test fails!

  array_a.barrier();
  // Check if array is allocated
  ASSERT_NE_U(array_a.lbegin(), nullptr);
  team_all.barrier();
}
```

I added the check `ASSERT_EQ_U(array_a.team(), myteam)`, which surprisingly fails. My understanding is that `array.team()` should yield the team the array was created with so the check should  succeed. Looking through the code, I don't see what could go wrong there. Ideas?

UPDATE: The error I get is

```
[  ERROR   ] [UNIT 0] in /home/joseph/src/dash/dash/dash/test/container/ArrayTest.cc:225
      Expected: array_a.team()
      Which is: dash::Team(0)
To be equal to: myteam
      Which is: dash::Team(1.0)
```

### PR DESCRIPTION
**Pull request by ddiefenthaler**
This pull request reverts the changes from PR #304 and solves it in a different way.

With the removal of the constructors from `BlockPattern` it got incompatible to the `CSRPattern`,
as the constructor of the `CSRPattern` differs in the signature.

To fix the ambiguity in the constructors this pull request removes some of the default paramters.
See also `TilePattern` for example, it is done there in the same way. [Parameter of `TilePattern` ctor](https://github.com/dash-project/dash/blob/development/dash/include/dash/pattern/TilePattern.h#L260#L265)

Due to the missing constructor the wrong constructor got called from `dash::Array` which lead to always using `dash::Team::All()` as the team of the array. This behaviour is observed in issue #353.

Fixes #353 and a part #292 (`ThreadsafetyTest.ConcurrentAlgorithm`).

### CODE REVIEW

**Comment by ddiefenthaler** [comment]
@devreal Can you add your adjusted unit test from issue #353?
Thanks for that by the way, it made debugging it quite a bit simpler
than having to jump between multiple threads to figure out where the team went wrong.

File: dash/include/dash/pattern/BlockPattern.h [hunk 1]
```diff
@@ -249,11 +249,10 @@ class BlockPattern
     /// Pattern size (extent, number of elements) in every dimension
     const SizeSpec_t         & sizespec,
     /// Distribution type (BLOCKED, CYCLIC, BLOCKCYCLIC, TILE or NONE) of
-    /// all dimensions. Defaults to BLOCKED in first, and NONE in higher
-    /// dimensions
```
Comment (fmoessbauer) [inline dash/include/dash/pattern/BlockPattern.h]: fix documentation (currently ends with "of")

**Review by fmoessbauer — COMMENTED** [review]
If that is everything that is necessary to fix the ambiguity this PR is great! Can you please cross-check if this still works for the Coarray. Nevertheless @fuchsto  or @devreal should have a look at the changes too.

File: dash/include/dash/pattern/BlockPattern.h (hunk 1 above)
Comment (ddiefenthaler) [reply dash/include/dash/pattern/BlockPattern.h]: Thats actually just a tricky way of git displaying it.
I fell for it too yesterday and repeated that commit.

File: dash/include/dash/pattern/BlockPattern.h [hunk 2]
```diff
@@ -249,11 +249,10 @@ class BlockPattern
...
-    const DistributionSpec_t & dist     = DistributionSpec_t(),
+    /// all dimensions.
```
Comment (ddiefenthaler) [inline dash/include/dash/pattern/BlockPattern.h]: @fmoessbauer Look here, there is the rest of the line.

**Comment by devreal** [comment]
@ddiefenthaler Great job, thanks a lot for the quick fix! I added the check to the `TeamSplit` test case and it succeeds. Since it's not my code, let's wait for the review from @fuchsto. 

While we are at it: Skimming through the code yesterday, I noticed that the `_arguments` in `BlockPattern` are stored in the pattern object even though they are only used in the c'tor. How about creating them temporarily and forwarding them to a private constructor? After all, they are rather heavy-weight. Maybe we could also apply some `constexpr` magic there because it's essentially just forwarding arguments (haven't tried though).

**Comment by fmoessbauer** [comment]
While we are at it: I fixed some other bugs in the CSR pattern as well. If you like, pull in (cherry-pick) [0609a02fd58e7](https://github.com/dash-project/dash/commit/0609a02fd58e7affa396e4f2ce8f61db1c9dd484). Btw: we definitely need concept checking on the patterns.

**Comment by ddiefenthaler** [comment]
I temporarily merged with [`feat-coarray`](https://github.com/dash-project/dash/tree/68e4459bb63ac91a244ab88645a7ee9c40e4633b), it was nearly automatic possible and test ran without problems.

If desired the constructor readded in this PR could get shortend by delegating to the other constructor
(like some constructors from [Array.h](https://github.com/dash-project/dash/blob/development/dash/include/dash/Array.h#L801)).

While being at cherry picking at CSRPattern I'll also add an constructor with the signatur
`CSRPattern(SizeSpec, DistSpec, TeamSpec, Team)`  so that it is more compatible to the other patterns.

**Comment by ddiefenthaler** [comment]
Delegating the constructor would look like this: 
```
  BlockPattern(
    /// Pattern size (extent, number of elements) in every dimension
    const SizeSpec_t         & sizespec,
    /// Distribution type (BLOCKED, CYCLIC, BLOCKCYCLIC, TILE or NONE) of
    /// all dimensions. Defaults to BLOCKED in first, and NONE in higher
    /// dimensions
    const DistributionSpec_t & dist = DistributionSpec_t(),
    /// Team containing units to which this pattern maps its elements
    Team                     & team = dash::Team::All())
  : BlockPattern(sizespec, dist, TeamSpec_t(_distspec, *_team), team)
  {
    DASH_LOG_TRACE("BlockPattern()", "(sizespec, dist, team)");
    DASH_LOG_TRACE("BlockPattern()", "finished delegation constructor");
  }
```
against the [current implementation](https://github.com/dash-project/dash/blob/bug-353-array-team/dash/include/dash/pattern/BlockPattern.h#L324-L360).

@devreal, @fuchsto is this preferred? This would be applicable to most patterns.

~Otherwise this pull request would be ready to merge in my opinion.~
EDIT: Sorry @devreal missed your comment on the second reading...
Of course it is not a bad idea to get rid of the `_arguments` member as it should be only needed during the construction.

**Comment by ddiefenthaler** [comment]
@fuchsto Here is a patch which would include the delegating constructors:
[Changed-ctor-of-pattern-to-delegate-to-similar-ctor.patch](https://github.com/dash-project/dash/files/888419/Changed-ctor-of-pattern-to-delegate-to-similar-ctor.patch.txt)

Apply it if you like,
Otherwise this pull request should be ready for review & merge

**Review by fuchsto — APPROVED** [review]
